syn on
set nu rnu ru cul mouse=a
set cin et ts=4 sw=4 sts=4
set autochdir
set clipboard=unnamedplus

colo koehler

no h b
no l e
no b l
no e h
no <C-h> ^
no <C-l> $
no ; :

inoremap {<CR> {<CR>}<Esc>ko

